// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Code.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Message {

  /// <summary>Holder for reflection information generated from Code.proto</summary>
  public static partial class CodeReflection {

    #region Descriptor
    /// <summary>File descriptor for Code.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CodeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpDb2RlLnByb3RvEgdNZXNzYWdlKpUCCgRDb2RlEgYKAk9rEAASCQoFRXJy",
            "b3IQARISCg5HYXRlU2lnbkZhaWxlZBACEhIKDkFjY291bnRJbGxlZ2FsEAMS",
            "EgoOUGxheWVyTm90Rm91bmQQBBISCg5Mb2dpbkVsc2V3aGVyZRAFEgwKCE5v",
            "dExvZ2luEAYSEgoNSXRlbU5vZEVub3VnaBCQThITCg5JdGVtSWROb3RFeGlz",
            "dBCRThIUCg9JdGVtVHlwZU5vdERlYWwQkk4SHAoXQWRkQ291bnRNdXN0Qmln",
            "Z2VyVGhhbjAQk04SEwoOQ29uZmlnTm90Rm91bmQQlE4SFAoPSXRlbU5vdEN1",
            "cnJlbmN5EJVOEhQKD1BsYXllck5vdE9ubGluZRCWTmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Message.Code), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum Code {
    [pbr::OriginalName("Ok")] Ok = 0,
    /// <summary>
    ///内部未知错误
    /// </summary>
    [pbr::OriginalName("Error")] Error = 1,
    /// <summary>
    /// gate校验失败
    /// </summary>
    [pbr::OriginalName("GateSignFailed")] GateSignFailed = 2,
    /// <summary>
    ///账号id非法
    /// </summary>
    [pbr::OriginalName("AccountIllegal")] AccountIllegal = 3,
    /// <summary>
    ///角色不存在
    /// </summary>
    [pbr::OriginalName("PlayerNotFound")] PlayerNotFound = 4,
    /// <summary>
    ///账号在其他地方登录
    /// </summary>
    [pbr::OriginalName("LoginElsewhere")] LoginElsewhere = 5,
    /// <summary>
    ///未在线 请重新登录
    /// </summary>
    [pbr::OriginalName("NotLogin")] NotLogin = 6,
    /// <summary>
    ///道具数量不足
    /// </summary>
    [pbr::OriginalName("ItemNodEnough")] ItemNodEnough = 10000,
    /// <summary>
    ///道具不存在
    /// </summary>
    [pbr::OriginalName("ItemIdNotExist")] ItemIdNotExist = 10001,
    /// <summary>
    ///道具类型未处理
    /// </summary>
    [pbr::OriginalName("ItemTypeNotDeal")] ItemTypeNotDeal = 10002,
    /// <summary>
    ///道具增加的数必须大于0
    /// </summary>
    [pbr::OriginalName("AddCountMustBiggerThan0")] AddCountMustBiggerThan0 = 10003,
    /// <summary>
    ///配置不存在
    /// </summary>
    [pbr::OriginalName("ConfigNotFound")] ConfigNotFound = 10004,
    /// <summary>
    ///道具不是货币类型
    /// </summary>
    [pbr::OriginalName("ItemNotCurrency")] ItemNotCurrency = 10005,
    /// <summary>
    ///玩家不在线
    /// </summary>
    [pbr::OriginalName("PlayerNotOnline")] PlayerNotOnline = 10006,
  }

  #endregion

}

#endregion Designer generated code
