// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Def.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Message {

  /// <summary>Holder for reflection information generated from Def.proto</summary>
  public static partial class DefReflection {

    #region Descriptor
    /// <summary>File descriptor for Def.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DefReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CglEZWYucHJvdG8SB01lc3NhZ2UqNwoISXRlbVR5cGUSDAoIY3VycmVuY3kQ",
            "ABIICgRpdGVtEAESCAoEaGVybxACEgkKBWVxdWlwEAMqPwoMQ3VycmVuY3lU",
            "eXBlEg8KC3BsYWNlaG9sZGVyEAASCAoEZ29sZBABEgsKB2RpYW1vbmQQAhIH",
            "CgNleHAQAypJCgZSYXJpdHkSCQoFV2hpdGUQABIJCgVHcmVlbhABEggKBEJs",
            "dWUQAhIKCgZQdXJwbGUQAxIKCgZPcmFuZ2UQBBIHCgNSZWQQBWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Message.ItemType), typeof(global::Message.CurrencyType), typeof(global::Message.Rarity), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum ItemType {
    /// <summary>
    ///货币
    /// </summary>
    [pbr::OriginalName("currency")] Currency = 0,
    /// <summary>
    ///道具
    /// </summary>
    [pbr::OriginalName("item")] Item = 1,
    /// <summary>
    ///英雄
    /// </summary>
    [pbr::OriginalName("hero")] Hero = 2,
    /// <summary>
    ///装备
    /// </summary>
    [pbr::OriginalName("equip")] Equip = 3,
  }

  /// <summary>
  /// IMessage //货币类型
  /// </summary>
  public enum CurrencyType {
    /// <summary>
    ///占位
    /// </summary>
    [pbr::OriginalName("placeholder")] Placeholder = 0,
    /// <summary>
    ///金币
    /// </summary>
    [pbr::OriginalName("gold")] Gold = 1,
    /// <summary>
    ///钻石
    /// </summary>
    [pbr::OriginalName("diamond")] Diamond = 2,
    /// <summary>
    ///玩家经验
    /// </summary>
    [pbr::OriginalName("exp")] Exp = 3,
  }

  /// <summary>
  ///稀有度
  /// </summary>
  public enum Rarity {
    [pbr::OriginalName("White")] White = 0,
    [pbr::OriginalName("Green")] Green = 1,
    [pbr::OriginalName("Blue")] Blue = 2,
    [pbr::OriginalName("Purple")] Purple = 3,
    [pbr::OriginalName("Orange")] Orange = 4,
    [pbr::OriginalName("Red")] Red = 5,
  }

  #endregion

}

#endregion Designer generated code
